Add controllers
no-fedov/java-shareit pull request #1
Opened 2024-04-21 07:50 UTC by no-fedov

ТЗ 13

2024-04-22 15:59 UTC, z8q requested changes

2024-04-22 15:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item addItem(@RequestHeader("X-Sharer-User-Id") Optional<Integer> userID,
В контроллерах надо будет поменять принимаемые и возвращаемые значения на dto.
экземпляры dto-классов нужны для валидации полей и хождения по логике приложения,
модели нужны для хранения, описания таблиц и описания зависимостей между таблицами.

Если сейчас приведем к такому виду, то последующую домашку с hibernate и базами будет немного проще выполнять.

2024-04-22 15:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item addItem(@RequestHeader("X-Sharer-User-Id") Optional<Integer> userID,
Про аннотацию RequestHeader.
Если в нее перейти, там есть параметр required, он по-дефолту выставлен на true, то есть является обязательным. Можно не делать Optional. Можно сделать обработку MissingRequestHeaderException в ExceptionController

2024-04-22 15:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
Валидационные аннотации нужно перенести в дто. Модели будут нужны только для хранения

2024-04-22 15:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    // этот тут не нужно ???
request будет в следующем спринте

2024-04-22 15:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/dto/ItemUpdateDto.java
> +public class ItemUpdateDto {
Для целей создания и обновления сущностей могут быть разные требования по валидации полей.
Можно ограничиться использованием одного класса дто, но с разными настройками валидации, если необходимо)

[На русском, блок "Группы валидаций"](https://struchkov.dev/blog/ru/spring-boot-validation/)
[На английском, блок "Using Validation Groups"](https://reflectoring.io/bean-validation-with-spring-boot/)

2024-04-22 15:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +    private UserMapper() {
Вместо такого конструктора можно поставить аннотацию над классом
```
@NoArgsConstructor(access = AccessLevel.PRIVATE)
```

2024-04-22 15:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +    private UserMapper() {
В мапперах методы можно привести к такому виду
```
private static ExampleDto mapToDto(Example example, тут при необходимости могут быть еще агрументы)
private static Example mapToModel(ExampleDto dto, тут при необходимости могут быть еще агрументы)
```
Вызовы будут выглядеть так
```
ExampleMapper.mapToDto(...)
ExampleMapper.mapToModel(...)
```

2024-04-22 15:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<Item> getAvailableItemsByName(@RequestParam Map<String, String> allParams) {
Можно принимать просто 
```
@RequestParam(name = "text") String text
```

2024-04-22 15:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImp.java
> +    private final Map<Integer, Map<Integer, Item>> userItems = new HashMap<>();
Надо еще придумать, как обновлять мапы, если будем удалять пользователя.
Будут ли удаляться все его вещи тоже

2024-04-23 12:54 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImp.java
> +    private final Map<Integer, Map<Integer, Item>> userItems = new HashMap<>();
зачем?

2024-04-23 12:55 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImp.java
> +    private final Map<Integer, Map<Integer, Item>> userItems = new HashMap<>();
не вижу смысла тратить на это время, если в след тз скажут организовать память в ДБ

2024-04-23 12:56 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/item/dto/ItemUpdateDto.java
> +public class ItemUpdateDto {
Использование групп проверки может легко стать анти-паттерном.
При использовании групп валидации сущность должна знать правила валидации для всех случаев использования (групп), в которых она используется.

с первого сайта

2024-04-23 18:43 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImp.java
> +    private final Map<Integer, Map<Integer, Item>> userItems = new HashMap<>();
Просто, чтобы потом не забыть, что такая логика будет нужна)
В базах это реализуется через каскадное удаление

2024-04-23 18:46 UTC, z8q approved these changes

2024-04-24 12:10 UTC, merged