Add bookings
no-fedov/java-shareit pull request #5
Opened 2024-05-25 10:29 UTC by no-fedov

2024-05-25 11:34 UTC, no-fedov commented
напутал с ветками, не знаю как удобнее проверять будет скорее всего этот коммит [Merge branch 'main' into add-bookings](https://github.com/no-fedov/java-shareit/pull/5/commits/b2b1e2203a2e0230a2d9ddedcfa207ee58ea7f60)

2024-05-26 11:27 UTC, z8q requested changes

2024-05-26 11:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingDto> findBookingByCondition(@RequestHeader("X-Sharer-User-Id") int userId,
Попробуй создать в ExceptionController еще два хэндлера
```JAVA
    @ExceptionHandler(MissingRequestHeaderException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public ExceptionWrapper handleMissingRequestHeaderException(MissingRequestHeaderException exception) {
        return new ExceptionWrapper(exception.getMessage());
    }

    @ExceptionHandler(MethodArgumentTypeMismatchException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public ExceptionWrapper handleMethodArgumentTypeMismatchException(MethodArgumentTypeMismatchException exception) {
        return new ExceptionWrapper(exception.getMessage());
    }
```

И потом сделать такой вызов
```
curl --request GET \
  --url http://localhost:8080/bookings \
  --header 'X-Sharer-User-Id: '
```
хэдер есть, но значение не указано

Если в методе findBookingByCondition для аргумента userId оставим примитивный тип int, придет такое сообщение
```
{
	"error": "Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: \"\""
}
```
Если исправим тип на обертку -  Integer userId, на такой же запрос будем получать более понятное сообщение
```
{
	"error": "Required request header 'X-Sharer-User-Id' for method parameter type Integer is present but converted to null"
}
```

Предложил поставить два хендлера, потому что, в зависимости от типа хедера, будут разные исключения

2024-05-26 11:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingDto> findBookingByCondition(@RequestHeader("X-Sharer-User-Id") int userId,
Если дополнительные хендлеры не сделать, то ошибочный запрос будет обрабатываться этим методом
```JAVA
    @ExceptionHandler
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    public Map<String, StackTraceElement[]> handleThrowableException(final Throwable e) {
        log.warn("Request processing error {}", e.getStackTrace());
        return Map.of("Request processing error", e.getStackTrace());
    }
```
А он вернет ответ, из которого ничего не понять. Можно про этот хэндлер тоже подумать

2024-05-26 11:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemPresentDto> getUserItems(@RequestHeader("X-Sharer-User-Id") int ownerId) {
Владелец видит даты последнего и ближайшего следующего бронирования для каждой вещи, когда просматривает список.

Сейчас даты не отображаются
```JSON
[
	{
		"id": 1,
		"owner": 1,
		"name": "car",
		"description": "Tesla",
		"available": true,
		"lastBooking": {
			"id": 1,
			"bookerId": 3
		},
		"nextBooking": null,
		"comments": []
	},
	{
		"id": 2,
		"owner": 1,
		"name": "car",
		"description": "Tesla",
		"available": true,
		"lastBooking": null,
		"nextBooking": null,
		"comments": []
	},
	{
		"id": 3,
		"owner": 1,
		"name": "car",
		"description": "Tesla",
		"available": true,
		"lastBooking": null,
		"nextBooking": null,
		"comments": []
	}
]
```

2024-05-26 11:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +        User currentUser = getCurrentUser(itemUpdateDto.getOwner());
Если поле не используется, можно убрать.
Сам вызов похоже используется для проверки на существования пользователя. Можно оставить

2024-05-26 11:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/dao/BookingOwnerRepository.java
> +    List<Booking> findByBookerIdAndItemIdAndStatusAndStartLessThan(@Param("bookerId") int bookerId,
Если не используем, можно убрать

2024-05-26 11:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/dto/BookingCreateDto.java
> +    private int booker;
Примитивы на null не проверяются
https://stackoverflow.com/questions/11047276/why-cant-primitive-data-types-be-null-in-java

2024-05-26 18:44 UTC, no-fedov commented on src/main/resources/schema.sql
> +MERGE INTO BOOKING_STATUS (status_name)
+

2024-05-26 18:44 UTC, no-fedov commented on src/main/resources/application.properties
> +logging.level.org.springframework.boot=TRACE
+

2024-05-26 18:45 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private final UserService userService;
+

2024-05-26 18:47 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemPresentDto> getUserItems(@RequestHeader("X-Sharer-User-Id") int ownerId) {
значит нет бронирования, все тесты постман под этот эндпоинт работают как нужно.

2024-05-26 18:49 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemPresentDto> getUserItems(@RequestHeader("X-Sharer-User-Id") int ownerId) {
![image](https://github.com/no-fedov/java-shareit/assets/145092682/b28dc810-42d5-4140-b596-9ff5004301d3)

2024-05-26 18:51 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +        User currentUser = getCurrentUser(itemUpdateDto.getOwner());
переменную убрал

2024-05-26 18:53 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/booking/dao/BookingOwnerRepository.java
> +    List<Booking> findByBookerIdAndItemIdAndStatusAndStartLessThan(@Param("bookerId") int bookerId,
убрал

2024-05-26 18:55 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingCreateDto.java
> +    private int booker;
исправил в контесте постман тестов

```
public class BookingCreateDto {
    
    private int booker;

    @NotNull
    private Integer itemId;
```

2024-05-26 19:03 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingDto> findBookingByCondition(@RequestHeader("X-Sharer-User-Id") int userId,
клево, супер!!!!!!!!

2024-05-27 18:00 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemPresentDto> getUserItems(@RequestHeader("X-Sharer-User-Id") int ownerId) {
В первом объекте есть одно бронирование
```JSON
"lastBooking": {
			"id": 1,
			"bookerId": 3
}
```

2024-05-27 18:03 UTC, z8q approved these changes

2024-05-30 13:48 UTC, merged