Add item requests
no-fedov/java-shareit pull request #6
Opened 2024-06-06 06:42 UTC by no-fedov

2024-06-09 18:39 UTC, z8q requested changes

2024-06-09 18:39 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        List<Integer> requestIds = requests.stream().map(Request::getId).collect(Collectors.toList());
Логику, которая дублируется в методе getPageRequest, можно выделить в общий метод

2024-06-09 18:39 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        Request newRequest = Request.builder()
Можно в маппер перенести

2024-06-09 18:39 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                bookings = bookingRepository.findByBookerIdOrderByStartDesc(userId, page);
Здесь и переменная получается не нужна, можно записать таким образом
```JAVA
switch (state) {
            case ALL:
                return BookingMapper.mapToListBookingDtoFromListBooking(
                        bookingRepository.findByBookerIdOrderByStartDesc(userId, page)
                );
            case PAST:
                return BookingMapper.mapToListBookingDtoFromListBooking(
                        bookingRepository.findByBookerIdAndEndLessThanOrderByStartDesc(userId, LocalDateTime.now(), page)
                );
//  остальные кейсы так же ...
}
```

2024-06-09 18:39 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/controller/RequestController.java
> +    private Pageable getPage(Integer from, Integer size) {
Есть в нескольких контроллерах,
можно выделить в какой-нибудь общий util-класс

2024-06-09 18:39 UTC, z8q commented on src/test/java/ru/practicum/shareit/request/dao/RequestRepositoryTests.java
> +@Sql(scripts = "/schema-test.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
Если использовать отдельную тестовую схему, надо следить, чтобы данные были актуальные, не расходились с основной схемой.
Сейчас есть небольшие расхождения,
где-то ON DELETE CASCADE не указан, 
для id в users NOT NULL в одной схеме указан, в другой нет

2024-06-10 12:35 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        List<Integer> requestIds = requests.stream().map(Request::getId).collect(Collectors.toList());
+++

2024-06-10 12:40 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                bookings = bookingRepository.findByBookerIdOrderByStartDesc(userId, page);
+++

2024-06-10 12:44 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/request/controller/RequestController.java
> +    private Pageable getPage(Integer from, Integer size) {
+++

2024-06-10 12:50 UTC, no-fedov commented on src/test/java/ru/practicum/shareit/request/dao/RequestRepositoryTests.java
> +@Sql(scripts = "/schema-test.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
+++

2024-06-10 13:00 UTC, no-fedov commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        Request newRequest = Request.builder()
+++

2024-06-10 19:20 UTC, z8q approved these changes

2024-07-18 13:26 UTC, merged